
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kaiwalya Kher
email: kaiwalya@kaiwalya.com
description: "Homepage of Kaiwalya Kher"
baseurl: ""
url: "https://kaiwalya.com"
twitter_username: kaiwalya
github_username:  kaiwalya


# Build settings
markdown: kramdown
permalink: pretty
analytics_id: "UA-40785129-1"

sass:
  sass_dir:          _sass
  style:            :compressed
